config/routes.rb
Coupan::Application.routes.draw do

  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      :registrations => "registrations"
    }

  root 'home#index'

  resources :coupons, only: [:index, :new, :create, :show, :update, :destroy]
  get '/users/:id/coupons', to: 'coupons#me', as: 'user_coupons'
  get '/oauth/', to: 'home#oauth_redirect'

  resource :api do
    member do
      get 'stores'
      get 'companies'
    end
  end

  get '/googlec41459c75d69b2af.html', to: 'home#google_valification'

end

app/models/coupon.rb
# 164,1512,3698,155,3556,
# 3104
class Coupon < ActiveRecord::Base
  belongs_to :user
  belongs_to :store

  default_scope { order('coupons.created_at DESC') }

  def score
    @score
  end
  def score=(score)
    @score = score
  end

  def recommend
    user_id = self.user_id
    store_id = self.store_id
    stamp = self.stamp
    max_stamp = self.store.max_stamp

    my_gender = User.find(self.user_id).gender
    my_coupons = {}
    for coupon in Coupon.where(:user_id => user_id)
      my_coupons[coupon.store_id] = coupon.stamp
    end

    user_ids_filter = Coupon.where(store_id: store_id).where("stamp >= ?", max_stamp - stamp)
    coupons = Coupon
      .where(user_id: user_ids_filter.map{|c| c.user_id})
      .where(store_id: my_coupons.keys)
      .where.not(user_id: user_id)

    other_users = {}
    for user in User.find(user_ids_filter.map{|u| u.user_id})
      other_users[user.id] = user.gender
    end

    scores = {}
    for c in coupons
      sid, uid = c.store_id, c.user_id
      scores[uid] = [] unless scores[uid]
      score = 1.0 - (((my_coupons[sid] + c.stamp) - max_stamp.to_f) / max_stamp.to_f).abs
      score += other_users[uid] != my_gender ? 1.0 : 0.0 unless other_users[uid]
      score += sid == store_id ? 1.0 : 0.0
      scores[uid] << c
      scores[uid][-1].score = score 
    end

	ret = scores.sort_by { |uid, coupons|
    s = coupons.map{|c| c.score}.sum
    s + coupons.size 
  }.reverse
	res = {}
	for (uid, coupons) in ret
	  res[uid] = coupons.sort_by{ |coupon| coupon.score}.reverse
	end
	res
  end

  def self.check_status(user_id)
    # stores = {}
    # for (store_id, user_with_scores) in Coupon.recommend(1, receive_coupon_ids)
    #   stores[store_id] = !user_with_scores.empty?
    # end
    # stores
    coupons = Coupon.where(:user_id => user_id)
    stores = {}
    for my_coupon in coupons
      stores[my_coupon.store_id] =
        Coupon.where(:store_id => my_coupon.store_id)
        .where("stamp >= ?", 10 - my_coupon.stamp).count == 0 ? false : true
    end
    stores
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :me, :show]
  before_action :get_places, only: [:new, :index]

  def index
    @coupons = Coupon.all
    if params[:place]
      @coupons = @coupons.eager_load(:store).where("stores.address_id=%s", params[:place])
    end

    @coupons = @coupons.page(params[:page])
    if request.xhr?
      return render 'coupons/_list', layout: false
    end
  end

  def destroy
    coupon = Coupon.find params[:id]
    coupon.destroy! if current_user == coupon.user

    redirect_to user_coupons_path(current_user)
  end

  def me
    @user = User.find params[:id]
    @coupons = Coupon.where(user_id: params[:id])
    uniq_address = @coupons.eager_load(:store).uniq.pluck("stores.address_id")
    @places = Address.where(id: uniq_address).select([:id, :name])

    if request.xhr?
      return render 'coupons/me/_list', layout: false
    end
    render 'me'
  end

  def show
    @coupon = Coupon.find params[:id]
    @recommend_coupons = @coupon.recommend
  end

  def update
    @coupon = Coupon.find params[:id]
    if params[:coupon].nil?
      stamp_count = 0
    else
      stamp_count = params[:coupon][:stamp].length
    end

    @coupon.update(stamp: stamp_count) if current_user == @coupon.user
    @recommend_coupons = @coupon.recommend
    render "coupons/_recommend_list", layout: false
  end

  def new
  end

  def create
    coupon = Coupon.new(coupon_params)
    if coupon.save
      return redirect_to user_coupons_path current_user
    end

    render 'coupon/new'
  end


  private def coupon_params
    user = current_user
    coupon = params[:coupon]
    max_stamp = coupon[:max_stamp]
    stamps = coupon[:stamp]
    store_name = coupon[:store] || ""
    store = Store.where(
        name: store_name.strip,
        max_stamp: max_stamp,
        address_id: coupon[:address]
      ).first_or_create
    store.save!

    params.require(:coupon).permit(:user, :stamp, :store).merge(
        user: user,
        stamp: stamps.count,
        store: store
      )
  end

  private def get_places
    @places = Address.all
  end

end

app/views/coupons/me/_item.html.haml
.portfolio-sec.media.mix{ data: { url: "#{coupon_path coupon}" }, rel: "coupon-link", class: "place_0 place_#{coupon.store.address_id}" }
  %a.pull-left{ href: "#"}
    %img.media-object.profile-image{ src: "#{coupon.user.image}" }
  .media-body
    .receive-coupon
      %h4.media-heading
        %span= coupon.store.name_with_address
        %span.pull-right= coupon.updated_at.strftime('%Y.%m.%d')
      .btn-group.stamp{"data-toggle" => "buttons"}
        - (1..coupon.stamp).each do
          %label.btn.btn-sm.btn-default.active{ disabled: true }
            %input{type: "checkbox", disabled: true}
        - ((coupon.stamp)+1..coupon.store.max_stamp).each do
          %label.btn.btn-sm.btn-default{ disabled: true }
            %input{type: "checkbox", disabled: true }

app/views/coupons/me/_list.html.haml
- if @coupons.present?
  - @coupons.each do |coupon|
    = render 'coupons/me/item', coupon: coupon
- else
  .text-center
    %h1 아이쿠!
    %p 등록하신 쿠폰이 없어요!!
    = link_to "Coupon", new_coupon_path, class: 'btn btn-lg new-coupon-btn'
    %p.small 위 버튼을 눌러서 새로운 쿠폰을 등록해주세요!!

app/views/coupons/me/_place.html.haml
- if @places.size > 1
  .space-10
  #place-query.col-md-12.text-center
    .btn-group.location{data: {toggle: "buttons"}}
      %label.btn.btn-sm.btn-default.active.filter{data: {filter: "place_0"}}
        %input{ type: "radio", checked: true } 전체

      - @places.each do |place|
        %label.btn.btn-sm.btn-default.filter{type: "button", data: {filter: "place_#{place['id']}"}}
          %input{ type: "radio" }= place['name']
  .space-20

app/views/coupons/me/_user.html.haml
- if controller.controller_name == 'coupons' and controller.action_name == 'me' and @coupons.present?
  #user-detail.col-md-12
    .portfolio-thumnail.text-center
      %a{href: "#"}
        %img.profile-image{alt: "", src: "#{@user.image}"}
    %ul.text-center.list-inline.list-unstyled
      %li.phone{ class: "#{ 'active' if @user.phone_number.present? and not @user.phone_number.nil? }"}
        - if user_signed_in?
          %a{href: "tel:#{@user.phone_number}", rel: "popover", data: {container: "body", toggle: "popover", placement: "top", content: "#{(@user.phone_number.present? ? @user.phone_number : "설정탭에서 전화번호를 적어주세요.")}"} }
            %i.fa.fa-mobile
            %span.small Phone
        - else
          %a{href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "top", content: "#{(@user.phone_number.present? ? "로그인해야만 볼 수 있습니다." : "설정탭에서 전화번호를 적어주세요.")}"} }
            %i.fa.fa-mobile
            %span.small Phone

      - if user_signed_in?
        %li.kakao{ class: "#{ 'active' if @user.kakao_id.present? and not @user.kakao_id.nil?}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "bottom", content: "#{(@user.kakao_id.present? ? @user.kakao_id : "설정탭에서 카카오톡 ID를 적어주세요.") }"}}
            %i.fa.fa-comments
            %span.small Kakao ID
      - else
        %li.kakao{ class: "#{ 'active' if @user.kakao_id.present? and not @user.kakao_id.nil?}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "bottom", content: "#{(@user.kakao_id.present? ? "로그인해야만 볼 수 있습니다." : "설정탭에서 카카오톡 ID를 적어주세요.") }"}}
            %i.fa.fa-comments
            %span.small Kakao ID


      - if user_signed_in?
        %li.company{ class: "#{ 'active' if @user.company.present? and not @user.company.nil?}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "top", content: "#{(@user.company.present? ? @user.company.name : "설정탭에서 직장이름을 적어주세요.")}"}}
            %i.fa.fa-flag
            %span.small Company
      - else
        %li.company{ class: "#{ 'active' if @user.company.present? and not @user.company.nil?}"}
          %a{ href: "#", rel: "popover", data: {container: "body", toggle: "popover", placement: "top", content: "#{(@user.company.present? ? "로그인해야만 볼 수 있습니다." : "설정탭에서 직장이름을 적어주세요.")}"}}
            %i.fa.fa-flag
            %span.small Company