config/routes.rb
Coupan::Application.routes.draw do

  devise_for :users, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks",
      :registrations => "registrations"
    }

  root 'home#index'

  resources :coupons, only: [:index, :new, :create, :show, :update, :destroy]
  get '/users/:id/coupons', to: 'coupons#me', as: 'user_coupons'
  get '/oauth/', to: 'home#oauth_redirect'

  resource :api do
    member do
      get 'stores'
      get 'companies'
    end
  end

  get '/googlec41459c75d69b2af.html', to: 'home#google_valification'

end

app/views/layouts/_alert_user_info_empty.html.haml
- if current_user and not current_user.phone_number.present? and not current_user.kakao_id.present?
  .row
    %a{href: "#{edit_user_registration_path}"}
      .alert.alert-sm.alert-warning
        사용자정보를 입력해주세요~
        %span.glyphicon.glyphicon-chevron-right.pull-right

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top.sticky-nav{role: "navigation"}
  .container
    .navbar-header
      - if current_user
        - if controller.controller_name == 'coupons' and controller.action_name == 'new'
          %a.navbar-toggle.collapsed.back-to-referer{type: "button", href: "#{(request.referer ? request.referer : coupons_path)}"}
            %span.sr-only Close add coupon
            %span.glyphicon.glyphicon-remove
        - else
          %a.navbar-toggle.collapsed{type: "button", href: "#{new_coupon_path}"}
            %span.sr-only Add Coupon
            %span.glyphicon.glyphicon-plus

      - elsif controller.controller_name != 'sessions'
        %a.navbar-toggle.collapsed{type: "button", href: "#{root_path}"}
          %span.sr-only Login
          %span.fa.fa-sign-in

      %a.navbar-brand{href: "#{coupons_path}"} Coupan

    .navbar-collapse.collapse{style: "height: 1px;"}
      - if current_user
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a{href: "#{new_coupon_path}"} Add Coupon
      - elsif controller.controller_name != 'sessions'
        %ul.nav.navbar-nav.navbar-right
          %li.dropdown
            %a{href: "#{root_path}"} Login

app/views/layouts/_meta.html.haml
%meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}
%meta{name: "viewport", content: "initial-scale=1.0,width=device-width,user-scalable=0, minimal-ui"}


/ SEO setting
%meta{content: "Coupan(쿠폰판교)", name: "Author"}
%meta{content: "사용하지 않은 쿠폰 서로 교환하세요~", name: "Description"}
%meta{content: "쿠폰, 판교, 쿠판, Coupon, Coupan", name: "Keyword"}
%meta{content: "noarchive", name: "robots"}
%meta{content: "xKC9MSkXkoOlnLWFsubV8oZiU-j8TZ7X8PorlGINN5g", name: "google-site-verification"}


/ Facebook og setting
%meta{content: "website", property: "og:type"}
%meta{content: "382538818551395", property: "fb:app_id"}
%meta{content: "Coupan(쿠폰판교)", property: "og:title"}
%meta{content: "http://coupan.so/", property: "og:url", rel: "canonical"}
%meta{content: "사용하지 않는 쿠폰 서로 교환하세요~", property: "og:description"}

-#
  / og image tags
  %meta{content: "https://lingring.net/static/image/logoFBOG_1.png", property: "og:image"}
  %meta{content: "image/png", property: "og:image:type"}
  %meta{content: "200", property: "og:image:width"}
  %meta{content: "200", property: "og:image:height"}

app/views/layouts/_nav.html.haml
- if current_user
  %nav.navbar.navbar-default.navbar-fixed-bottom{role: "navigation"}
    .container
      .row
        %ul.list-unstyled.list-inline.text-center
          %li.col-xs-4{ class: "#{'active' if controller.controller_name == 'coupons' and controller.action_name == 'index' }"}
            %a{href: "#{coupons_path}"}
              %i.fa.fa-list
              %span.help-text 전체 쿠폰
          %li.col-xs-4{ class: "#{'active' if (controller.controller_name == 'coupons' and controller.action_name == 'me') or (@coupon and @coupon.user == current_user) }"}
            %a{href: "#{user_coupons_path current_user.id}"}
              %i.fa.fa-user
              %span.help-text 내 쿠폰
          %li.col-xs-4{ class: "#{'active' if controller.controller_name == 'registrations'}"}
            %a{href: "#{edit_user_registration_path}"}
              %i.fa.fa-ellipsis-h
              %span.help-text 설정

app/views/layouts/application.html.haml
!!!
%html
  %head
    = render 'layouts/meta'

    %title Coupan(쿠폰판교)

    = stylesheet_link_tag 'font-awesome'
    = stylesheet_link_tag 'application'

    %link{href: "http://fonts.googleapis.com/css?family=Raleway:400,300,100,700,800,500", rel: "stylesheet", type: "text/css"}
    %link{href: "http://fonts.googleapis.com/css?family=Playfair+Display:400italic", rel: "stylesheet", type: "text/css"}
    /[if lt IE 9]
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>]
    = stylesheet_link_tag params[:controller]
    = yield :page_specific_stylesheets

    = javascript_include_tag 'application'
    = yield :page_specific_head_scripts
    = javascript_include_tag params[:controller]

    = csrf_meta_tags

  %body
    = render "layouts/header"

    /
      <haml_loud> link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) </haml_loud>

    #content.container
      = render 'layouts/alert_user_info_empty'
      = content_for?(:contents) ? yield(:contents) : yield

    = render "layouts/nav"

    = yield :page_specific_scripts